[package]
name = "bevy_ggrs_fighting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
bevy = {version = "0.7", features = ["serialize"]}
bevy_ggrs = { git = "https://github.com/gschup/bevy_ggrs"}
ggrs = { git = "https://github.com/gschup/ggrs", features=["sync-send"]}

ruwren = "0.4.2"

bitflags = "1.3"
ux = "0.1.4"
bytemuck = {version="1.7.3", features= ["derive"]}

serde = "1.0.137"
serde_json = "1.0.81"