[package]
name = "bevy_ggrs_fighting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3



[dependencies]
structopt = "0.3"
bevy = {version = "0.8", features = ["serialize"]}
#bevy_ggrs = { git = "https://github.com/gschup/bevy_ggrs"}
bevy_ggrs = { git = "https://github.com/paxsethorld/bevy_ggrs" }
ggrs = { git = "https://github.com/gschup/ggrs", features=["sync-send"]}

#bevy_mod_scripting = { git = "https://github.com/makspll/bevy_mod_scripting", rev = "c0eb34e", features = ["teal"] }
#tealr = {git = "https://github.com/lenscas/tealr"}
#tealr = { git = "https://github.com/lenscas/tealr", features = ["mlua_vendored","mlua_send"], branch="feature/document_global_instances" }

bitflags = "1.3"
ux = "0.1.4"
bytemuck = {version="1.7.3", features= ["derive"]}
regex = "1"
packed_struct = "0.10.0"

serde = "1.0.137"
serde_json = "1.0.81"
serde_closure = "0.3.2"
typetag = "0.2.0"
bevy_common_assets = {version = "0.3.0", features = ["json"]}
iyes_loopless = "0.7.0"
iyes_progress = {version = "0.4.0", features = ["assets", "iyes_loopless"]}
#iyes_progress = { git = "https://github.com/IyesGames/iyes_progress", rev = "4db0576", features = ["assets", "iyes_loopless"] }
bevy_prototype_lyon = "0.6.0"

#bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls" }
bevy-inspector-egui = "0.12.1"
#bevy_prototype_frametime_display_plugin = { git = "https://github.com/IceSentry/bevy_prototype_frametime_display_plugin" }

#required because above doesn't reimport Inspectable
#bevy-inspector-egui = "0.8.0"